import Head from 'next/head'
import Link from 'next/link'
import NewsBox from '../components/NewsBox'


export default function Home() {
  return (
    <div>
      <Head>
        <title>NewsHub</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <span>
      <Link href={'/entertainment'} passHref>Entertainment</Link>
      </span>
      <span>
        <Link href={'/sports'} passHref>Sports</Link>
      </span>
      <NewsBox/>
    </div>
  )
}
